### ISSUE TITLE
Entweder nebeneinander oder neue zeile und untereinander: Function(

### ISSUE THREAD

**Issue by Nex0TV** [Nex0TV/taschenrechner_it20-1_Team_2#12]
formatierung ist komisch
würde es abändern zu:

```
... double static Calculate(
        int colorDepth = 0,
        ...
        int imageSize = 0
)
```

_Originally posted by @benjaminproductions in https://github.com/Nex0TV/taschenrechner_it20-1_Team_2/pull/8#discussion_r1099732260_

**Comment by FabiusGruener** [comment]
Adjusted in new commit
